### ISSUE TITLE
only one result printed for config file interface

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel-bench#113]
I am using this:
```
global_options:
  project_commit: 10eddc3d5394d2483b0568c6f88f6954fc380158
  runs: 5
  collect_profile: True
  project_source: /usr/local/google/home/twerth/bazel
  bazel_binary: /usr/bin/bazel-real
units:
  - command: build --jobs=100 //src:bazel
  - command: build --jobs=600 //src:bazel
```

prints:
```
RESULTS:
Bazel commit: /usr/bin/bazel-real, Project commit: 10eddc3d5394d2483b0568c6f88f6954fc380158, Project source: /usr/local/google/home/twerth/bazel
  metric          mean                median          stddev      pval   
    wall:  111.753s             111.931s              0.622s             
     cpu:  124.410s             124.550s              3.667s             
  system:   52.578s              52.810s              0.885s             
  memory:   95.600MB             96.000MB             0.490MB   
```
which is only the result of the second run.
