### ISSUE TITLE
Include task-specific shell commands and build flags

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel-bench#46]
**Description of the problem / feature request:**

For example: https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml#L119
```
ubuntu1804_javabase9:
    platform: ubuntu1804_nojava
    name: ":java: OpenJDK 9 Javabase"
    shell_commands:
      - sed -i.bak -e 's/^# android_sdk_repository/android_sdk_repository/' -e 's/^#
        android_ndk_repository/android_ndk_repository/' WORKSPACE
      - rm -f WORKSPACE.bak
    build_flags:
      - "--javabase=@openjdk9_linux_archive//:runtime"
...
ubuntu1804_javabase10:
    platform: ubuntu1804_nojava
    name: ":java: OpenJDK 10 Javabase"
    shell_commands:
      - sed -i.bak -e 's/^# android_sdk_repository/android_sdk_repository/' -e 's/^#
        android_ndk_repository/android_ndk_repository/' WORKSPACE
      - rm -f WORKSPACE.bak
    build_flags:
      - "--javabase=@openjdk10_linux_archive//:runtime"
```

The same `ubuntu1804_nojava` platform can have many tasks based on it, each with a different set of `shell_commands` and `build_flags`.

It's useful to perform benchmarking on each of these different environments.
